### ISSUE TITLE
Add Tags property for Post

### ISSUE THREAD

**Issue by LewieMac** [ButterCMS/buttercms-csharp#10]
I haven't been able to find a Tags field for the Post class. I was expecting an IEnumerable<Tag> Tags property there or am I doing something wrong?

**Comment by jakelumetta** [comment]
Hey Lewis. We’re looking into this.

**Comment by jakelumetta** [comment]
@LewieMac Please update to `1.3.2` and try again. Let us know if you're still experiencing issues.
