### ISSUE TITLE
It is at all possible to expose a unique identifier for posts?

### ISSUE THREAD

**Issue by Tiger333** [ButterCMS/buttercms-csharp#23]
At the moment the only identifier we can use is the 'slug' but of course the 'slug' can be changed.
Within butterCMS there appears to be a numeric identifier for each post.

Is it possible to expose this 'unique' identifier?

For my specific user case I want to log custom events and analytics against specific 'posts' but in order to do this I need a stable identifier to use - whilst i can use the slug i've had causes in which the slug has been changed.

With 'pages' i know it's potentially possible to create a custom property that 'could' be used to accomplish the same thing, but that does appear to be a lot of leg work in order to gain access to something so simple (in theory..)

**Comment by jonalecpalustre** [comment]
@Tiger333 You can use our webhook for this use case. Our webhook returns `_id` for each blog post.
I'd suggest to reach out and chat with our Support team directly too so we can see all the details in your account and provide better support. Thanks!
