### ISSUE TITLE
Install-Package ButterCMS Error

### ISSUE THREAD

**Issue by crono009** [ButterCMS/buttercms-csharp#7]
While trying to install ButterCMS, I run into the following error.

> Install failed. Rolling back...
> Package 'ButterCMS.1.3.0 : Newtonsoft.Json [10.0.3, ), System.Net.Http [4.3.0, )' does not exist in project 'BlogTest'
> Package 'ButterCMS.1.3.0 : Newtonsoft.Json [10.0.3, ), System.Net.Http [4.3.0, )' does not exist in folder 'C:\Users\User1\Source\Repos\blogtest\packages'
> 
> Install-Package : Could not install package 'ButterCMS 1.3.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not 
> contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I have tried making a clean project and installing the ButterCMS package and have also tried installing it on different machines, however I get the same error. After some googling, I've determined that perhaps this may be due to some issues with resolving the dependencies. I tested ButterCMS around 3 months ago and it seemed to work fine then. Any idea what the issue may be?

Thanks!

**Comment by bgnicoll** [comment]
A temporary workaround would be to change your project from .NET Framework v4.5 to .NET Framework v4.6.1. I'm investigating how the library can be expanded to allow more versions of the .NET Framework and will update this issue when I am successful.

**Comment by bgnicoll** [comment]
Hi! I just opened a PR to allow .NET 4.5 compatibility. I'll report back here once the package makes it to Nuget

**Comment by jakelumetta** [comment]
@crono009 Please update to 1.3.1 and let us know if that works  - https://www.nuget.org/packages/ButterCMS/

**Comment by jakelumetta** [comment]
@crono009  Any luck? I'm closing this issue for now. Please let us know if you're still experiencing issues.
