### ISSUE TITLE
.net Core

### ISSUE THREAD

**Issue by kensel** [ButterCMS/buttercms-csharp#8]
I would like to request instructions for using with .net core 2.0.
This would also allow for the library to be cross platform with .net core 2.0 and asp.net core 2.0.

**Comment by bgnicoll** [comment]
Hi, the PR I just opened should address these concerns

**Comment by jakelumetta** [comment]
@kensel Please update to 1.3.1 and let us know if that works  - https://www.nuget.org/packages/ButterCMS/

**Comment by jakelumetta** [comment]
@kensel Any luck? I'm closing this issue for now. Please let us know if you're still experiencing issues.
